version: '3'

networks:
  supply_chain_carbon:
    name: supply_chain_carbon
    external: true

services:
  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - supply_chain_carbon