version: "3.7"

volumes:
  orderer3.example.com:

networks:
  supply_chain_carbon:
    name: supply_chain_carbon
    external: true

services:
  orderer3.example.com:
    container_name: orderer3.example.com
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer3.example.com:11443
    working_dir: /root
    command: orderer
    volumes:
      - ../../channel-artifacts/carbonchannel.block:/etc/hyperledger/orderer/orderer.genesis.block
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/etc/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/etc/hyperledger/orderer/tls
      - orderer3.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
      - 9053:9053
      - 11443:11443
    networks:
      - supply_chain_carbon
