version: '3.7'

networks:
  supply_chain_carbon:
    name: supply_chain_carbon
    external: true

services:

  ca_kementrian:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca_kementrian
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-kementrian
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../organizations/fabric-ca/kementrian:/etc/hyperledger/fabric-ca-server
    networks:
      - supply_chain_carbon

  ca_orderer:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca_orderer
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    networks:
      - supply_chain_carbon
