version: '3.7'

networks:
  supply_chain_carbon:
    name: supply_chain_carbon
    external: true

services:

  ca_supplychain:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca_supplychain
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-supplychain
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../organizations/fabric-ca/supplychain:/etc/hyperledger/fabric-ca-server
    networks:
      - supply_chain_carbon
